name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 12 * * *'  # Runs every day at 6PM GMT+6 (12PM UTC)
  workflow_dispatch:       # Allows manual trigger from GitHub

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/Vencord/Vencord.git
          git fetch upstream

      - name: Set up merge strategy for userplugins
        run: |
          git config merge.ours.driver true

      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --strategy-option theirs --allow-unrelated-histories || echo "Manual merge required"
          git push origin main
